/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import hotel.hotelbooking.Customer;
import hotel.hotelbooking.Booking;
import hotel.hotelbooking.DBConnection;
import hotel.hotelbooking.Room;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.time.LocalDate;
/**
 *
 * @author ALAKSA
 */
public class BookingForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookingForm.class.getName());

    /**
     * Creates new form BookingForm
     */
    public BookingForm() {
        initComponents();
        loadCustomers();
    loadRooms();
        
        
        
        
        //==========================================================================
         Connection conn = DBConnection.getConnection();

    if (conn != null) {
        System.out.println("Connection OK ✔️");
    } else {
        System.out.println("Connection Failed ❌");
    }
    }
    //========================================================
private void loadCustomers() {
    // كود تعبئة العملاء
    try {
        java.sql.Connection conn = DBConnection.getConnection();
        java.sql.PreparedStatement ps = conn.prepareStatement(
            "SELECT id, name FROM customer");
        java.sql.ResultSet rs = ps.executeQuery();
        
        jComboBox1.removeAllItems();
        while (rs.next()) {
            jComboBox1.addItem(rs.getInt("id") 
                + " - " + rs.getString("name"));
        }
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "خطأ: " + e.getMessage());
    }
    
}

private void loadRooms() {
    // كود تعبئة الغرف
    // تعبئة ComboBox بالغرف
    try {
        java.sql.Connection conn = DBConnection.getConnection();
        java.sql.PreparedStatement ps = conn.prepareStatement(
            "SELECT roomNumber, type FROM room");
        java.sql.ResultSet rs = ps.executeQuery();
        
        jComboBox2.removeAllItems();
        while (rs.next()) {
            jComboBox2.addItem(rs.getInt("roomNumber") 
                + " - " + rs.getString("type"));
        }
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "خطأ: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton JOptionPane1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JOptionPane1.setText("BOOK");
        JOptionPane1.addActionListener(this::JOptionPane1ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("BOOKING");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("CUSTOMER ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ROOM ");

        jButton1.setText("prview");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(JOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JOptionPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JOptionPane1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOptionPane1ActionPerformed
try {
        // قراءة البيانات
        String customerStr = jComboBox1.getSelectedItem().toString();
        int customerId = Integer.parseInt(customerStr.split(" - ")[0]);
        String customerName = customerStr.split(" - ")[1];

        String roomStr = jComboBox2.getSelectedItem().toString();
        int roomNumber = Integer.parseInt(roomStr.split(" - ")[0]);
        String roomType = roomStr.split(" - ")[1];

        // حفظ في قاعدة البيانات
        java.sql.Connection conn = DBConnection.getConnection();
        String sql = "INSERT INTO booking (id, name, roomNumber, type) "
                   + "VALUES (?, ?, ?, ?)";
        java.sql.PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, customerId);
        ps.setString(2, customerName);
        ps.setInt(3, roomNumber);
        ps.setString(4, roomType);

        int result = ps.executeUpdate();

        if (result > 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "✅ تم الحجز بنجاح!");
            printBookingReport(customerId, customerName,
                               roomNumber, roomType);
        }

        ps.close();
        conn.close();

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "❌ خطأ: " + e.getMessage());
    }
}

private void printBookingReport(int id, String name,
                                int roomNumber, String type) {
    try {
        String report =
            "================================\n" +
            "     HOTEL BOOKING RECEIPT      \n" +
            "================================\n" +
            "Customer IDرقم الزبون   : " + id + "\n" +
            "Customer Name اسم الزبون   : " + name + "\n" +
            "Room Number   رقم الغرقة: " + roomNumber + "\n" +
            "Room Type    نوع الغرقة : " + type + "\n" +
            "Date      التاريخ    : " +
            java.time.LocalDate.now() + "\n" +
            "================================\n" +
            "    Thank You For Booking!   شكراً   \n" +
            "================================\n";

        java.awt.print.PrinterJob job =
            java.awt.print.PrinterJob.getPrinterJob();

        job.setPrintable((graphics, pageFormat, pageIndex) -> {
            if (pageIndex > 0)
                return java.awt.print.Printable.NO_SUCH_PAGE;
            graphics.setFont(new java.awt.Font(
                "Monospaced", java.awt.Font.PLAIN, 12));
            String[] lines = report.split("\n");
            int y = 100;
            for (String line : lines) {
                graphics.drawString(line, 100, y);
                y += 20;
            }
            return java.awt.print.Printable.PAGE_EXISTS;
        });

        if (job.printDialog()) {
            job.print();
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "❌ خطأ في الطباعة: " + e.getMessage());
    }
       
    }//GEN-LAST:event_JOptionPane1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Dashboard d1=new Dashboard();
d1.setVisible(true);
this.setVisible(false);      

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookingForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
